version: '3.6'
services:
  selenoid:
    network_mode: bridge
    image: docker-virtual/aerokube/selenoid:latest
    container_name: "selenoid"
    volumes:
    - ./browsers.json:/etc/selenoid/browsers.json
    - "$PWD/selenoid:/opt/selenoid"
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "$PWD/selenoid/video:/opt/selenoid/video"
    - "$PWD/selenoid/logs:/opt/selenoid/logs"
    environment:
    - OVERRIDE_VIDEO_OUTPUT_DIR=$PWD/selenoid/video
    command: ["-limit", "10" , "-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs"]
    ports:
    - "4444:4444"
