name: demo-actions

on: [ push, workflow_dispatch ]

jobs:
  run-demo-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Start selenoid
        uses: Xotabu4/selenoid-github-action@v2

      - name: Run demo test
        run: mvn clean test -Dtest=**/*DemoSuite.class -DfailIfNoTests=false -Ddriver.remote=true

      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: target/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
          keep_files: true

      - name: Publish allure artifact
        if: always()
        uses: actions/upload-artifact@v3.1.0
        with:
          name: allure-artifact
          path: target/allure-results/

      - name: Post the link to the report
        if: always()
        uses: Sibz/github-status-action@v1.1.6
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          context: 'Link to Allure report'
          state: 'success'
          sha: ${{ github.event.pull_request.head.sha }}
          target_url: vafanasenka-frontlineed.github.io/demo/${{ github.run_number }}